Add new OpenAI embedding models + dimensions parameter
RageAgainstThePixel/OpenAI-DotNet pull request #226
Opened 2024-01-25 20:41 UTC by Mitch528

This PR adds the new OpenAI embeeding models, as announced here:

https://openai.com/blog/new-embedding-models-and-api-updates

Also added the new `dimensions` parameter described in the announcement.

2024-01-25 20:51 UTC, StephenHodgson commented on OpenAI-DotNet/Models/Model.cs
> +        public static Model Embedding_3_Large { get; } = new("text-embedding-3-large", "openai");
lets add descriptions for these models.

2024-01-25 20:51 UTC, StephenHodgson commented on OpenAI-DotNet/Embeddings/EmbeddingsEndpoint.cs
> +
```suggestion

```

2024-01-25 20:52 UTC, StephenHodgson commented on OpenAI-DotNet-Tests/TestFixture_06_Embeddings.cs
> +        public async Task Test_1_CreateEmbeddingWithDimensions()
```suggestion
        public async Task Test_2_CreateEmbeddingWithDimensions()
```

2024-01-25 20:52 UTC, StephenHodgson requested changes
See comments

2024-01-25 21:01 UTC, Mitch528 commented
> See comments

updated!

2024-01-26 03:18 UTC, StephenHodgson approved these changes

2024-01-26 03:18 UTC, merged