refactor: Add support for multiple inputs in EmbeddingsRequest
RageAgainstThePixel/OpenAI-DotNet pull request #33
Opened 2023-03-04 12:35 UTC by ZeekoZhu

This pr adds support for multiple inputs in the EmbeddingsRequest class. The input parameter can now be a string or an array of strings. The constructor has been updated to handle both cases, and a new constructor has been added to accept an array of strings. The Input property has been changed to an IList<string> to accommodate the new functionality.

2023-03-04 15:46 UTC, StephenHodgson submitted a review, later dismissed
This looks great! Could we also add unit tests and bump the version and add change log?

Thanks

2023-03-05 09:15 UTC, ZeekoZhu commented
@StephenHodgson done, please review

2023-03-06 16:20 UTC, StephenHodgson commented on OpenAI-DotNet-Tests/TestFixture_05_Embeddings.cs
> +                new[] { "The food was delicious and the waiter...", "The food was terrible and the waiter..." });
let's either break this out into a local variable or make it one line.

2023-03-06 16:20 UTC, StephenHodgson commented on OpenAI-DotNet/Embeddings/EmbeddingsEndpoint.cs
> +            string user = null)
Please make all one line for parameters

2023-03-06 16:20 UTC, StephenHodgson commented on OpenAI-DotNet/Embeddings/EmbeddingsRequest.cs
> +
not an extra space here

2023-03-06 16:21 UTC, StephenHodgson commented on OpenAI-DotNet/Embeddings/EmbeddingsRequest.cs
> +        public EmbeddingsRequest(IList<string> input, Model model = null, string user = null)
```suggestion
        public EmbeddingsRequest(List<string> input, Model model = null, string user = null)
```

2023-03-06 16:21 UTC, StephenHodgson commented on OpenAI-DotNet/Embeddings/EmbeddingsRequest.cs
> +        public IList<string> Input { get; }
```suggestion
        public List<string> Input { get; }
```

2023-03-06 16:22 UTC, StephenHodgson commented on OpenAI-DotNet/Embeddings/EmbeddingsRequest.cs
> +            if (input.Count == 0)
We should also check if it's null, just in case

2023-03-06 16:22 UTC, StephenHodgson requested changes
See comments

2023-03-06 17:16 UTC, merged