Support ToolCalls within the conversation history
RageAgainstThePixel/OpenAI-DotNet pull request #341
Opened 2024-07-29 16:50 UTC by henduck

Added a new public Tool constructor (and internal Function constructor) for assistant-invoked tool calls within the conversation history (setting ToolCallId, Function.Name, and Function.Arguments)

Proposed solution to address [this issue](https://github.com/RageAgainstThePixel/OpenAI-DotNet/issues/340)

2024-07-29 17:15 UTC, StephenHodgson commented
I'll take a look shortly. Thanks for the contribution!

2024-08-09 15:04 UTC, jesses-avi commented
Hi @StephenHodgson  ...do you have a sense of when you might be able to look at this PR?  I'm just trying to plan out my own timeline for addressing the use case this covers... and if it will be a long time before this is resolved, I'll just have to pursue an alternative path. I of course understand if this may not be your highest priority project, and appreciate your work on it in any case.

Thanks in advance!!

2024-08-09 15:08 UTC, StephenHodgson commented
bump the minor version and I'll run the unit tests and make a release if they pass

2024-08-09 16:31 UTC, henduck commented
Awesome... done. Thanks!

2024-08-09 17:56 UTC, StephenHodgson commented on OpenAI-DotNet/OpenAI-DotNet.csproj
> +    <Version>8.2.0</Version>
8.1.2

2024-08-09 17:57 UTC, StephenHodgson requested changes
we don't need to bump that far

2024-08-09 18:29 UTC, henduck commented on OpenAI-DotNet/OpenAI-DotNet.csproj
> +    <Version>8.2.0</Version>
Gotcha... updated

2024-08-09 19:37 UTC, StephenHodgson commented
All unit tests passed locally

2024-08-09 19:37 UTC, merged