HttpRequestException fix on different character sets
RageAgainstThePixel/OpenAI-DotNet pull request #59
Opened 2023-03-21 15:31 UTC by SamKr

Proposed fix for #57 

After digging around, it appears that this is common for proxies. The `Transfer-Encoding` header gets added, set to `chunked`, which throws the client off. 

It functions when the header is removed. 

Note: it appears to have no side effects, but I have only tested casually.

2023-03-21 15:36 UTC, SamKr commented
Sidenote: this can't be fixed by simply adding an encoding parameter or any other parameter for that matter (as far as I can tell).

2023-03-21 15:54 UTC, StephenHodgson commented on OpenAI-DotNet/Proxy/OpenAIProxyStartup.cs
> +                    if (header.Key == "Transfer-Encoding") continue;
can we add this to a pre-defined readonly collection?

2023-03-21 15:57 UTC, StephenHodgson commented on OpenAI-DotNet/Proxy/OpenAIProxyStartup.cs
> +                    if (header.Key == "Transfer-Encoding") continue;
This is a good reference: 
https://github.com/microsoft/reverse-proxy/blob/51d797986b1fea03500a1ad173d13a1176fb5552/src/ReverseProxy/Forwarder/RequestUtilities.cs#L61-L83

2023-03-21 16:00 UTC, StephenHodgson commented on OpenAI-DotNet/Proxy/OpenAIProxyStartup.cs
> +                    if (header.Key == "Transfer-Encoding") continue;
https://github.com/microsoft/reverse-proxy/tree/51d797986b1fea03500a1ad173d13a1176fb5552/src/ReverseProxy/Forwarder

2023-03-21 16:01 UTC, StephenHodgson requested changes
I changed the base branch to development, and needs to be synced with upstream changes. It seems there's a conflict. 

I moved the proxy into it's own project directory.

2023-03-21 18:45 UTC, StephenHodgson commented
@SamKr I opened a PR with [the expected changes](#60) I'd like to see for this PR. Please make the changes and I'll merge this one in.

2023-03-21 19:47 UTC, SamKr commented
Will do tomorrow, long day at work :)

2023-03-22 08:31 UTC, SamKr commented
Closing because of #60

2023-03-22 08:31 UTC, closed without merging

2023-03-22 13:05 UTC, StephenHodgson commented
You sure? I was going to close mine in favor of yours after you updated it with the changes I requested so that you would get recognition for it in the project.

2023-03-22 13:15 UTC, SamKr commented
No worries, I'm just glad it's fixed 😄

2023-03-22 13:16 UTC, StephenHodgson commented
I appreciate you taking the time! I had tested this out briefly but hadn't really given it through the paces.